### ISSUE TITLE
Napari 0.5.3 installed from bundle file is interupted when installing plugins on UI

### ISSUE THREAD

**Issue by hnguyentt** [napari/napari-plugin-manager#103]
### 🐛 Bug Report

I installed Napari 0.5.3 from Bundle file. When I opened Napari &#8594; clicked <kbd>Plugins</kbd> &#8594; <kbd>Install/Uninstall Plugins ...</kbd>, the app closed immediately without any error messages.

### 💡 Steps to Reproduce

1. Download installation file here: https://github.com/napari/napari/releases/tag/v0.5.3
2. Install following this instruction: https://napari.org/stable/tutorials/fundamentals/installation_bundle_conda.html#how-to-install-the-linux-bundle
3. Open Napari
4. <kbd>Plugins</kbd> &#8594; <kbd>Install/Uninstall Plugins ...</kbd>

### 🌎 Environment

napari: 0.5.3
Platform: Ubuntu 22.04.3 - kernel: 6.8.0-40-generic
Python: 3.9.19

**Comment by dalthviz** [comment]
Giving this a check, seems like the bundle comes with PySide2 and doing `from napari_plugin_manager.qt_plugin_dialog import QtPluginDialog` causes a crash 🤔

![imagen](https://github.com/user-attachments/assets/c90d12fb-f37f-479e-b960-e4021f93a33c)

Maybe this is related with https://github.com/napari/napari-plugin-manager/issues/94 ?

**Comment by psobolewskiPhD** [comment]
PySide2! *shakes tiny fist*

**Comment by dalthviz** [comment]
Seems like the line where things crash is:

https://github.com/napari/napari-plugin-manager/blob/9be404ab2a16f7bd8b578a5e5390267ee5b7a4d9/napari_plugin_manager/qt_plugin_dialog.py#L107-L109

Most probably creating a signal which should handle `StringEnum` subclasses makes things crash (I think PySide does some stuff with Enums 🤔)

Changing the signal definition to be something like:

```python
actionRequested = Signal(
        QListWidgetItem, str, StringEnum, str, StringEnum
    )
```
or

```python
actionRequested = Signal(
        QListWidgetItem, str, str, str, str
    )
```

Seems like helps 🎉
