### ISSUE TITLE
Create new release to include pyside fix on windows and any other patches worked on the week

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#105]

**Comment by dalthviz** [comment]
@jaimergp @goanpeca created a v0.1.2 release:

* GitHub release: https://github.com/napari/napari-plugin-manager/releases/tag/v0.1.2
* PyPI: https://pypi.org/project/napari-plugin-manager/0.1.2/
* conda-forge related issue/PR to update recipe (needs approval and merge): https://github.com/conda-forge/napari-plugin-manager-feedstock/issues/6 and https://github.com/conda-forge/napari-plugin-manager-feedstock/pull/7

Let me know if something else is needed!

**Comment by dalthviz** [comment]
Due to #106 and after #107 gets merged, could it be worthy to release v0.1.3?

**Comment by jaimergp** [comment]
Let's do it!

**Comment by dalthviz** [comment]
v0.1.3 released! (pending conda-forge recipe PR merge):

* GitHub release: https://github.com/napari/napari-plugin-manager/releases/tag/v0.1.3
* PyPI: https://pypi.org/project/napari-plugin-manager/0.1.3
* conda-forge issue and PR (PR needs approval/merge): https://github.com/conda-forge/napari-plugin-manager-feedstock/issues/8, https://github.com/conda-forge/napari-plugin-manager-feedstock/pull/9

**Comment by psobolewskiPhD** [comment]
I approved, but might be worth just adding the auto-merge?
https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-bot-automerge

**Comment by jaimergp** [comment]
Merged! Thanks @dalthviz!
