### ISSUE TITLE
Plugin dialog requests

### ISSUE THREAD

**Issue by ppwadhwa** [napari/napari-plugin-manager#14]
## 🚀 Feature

While working on napari/napari#5198, there were a few requests that were outside of the scope of the PR or were "nice to have" items.  I wanted to document them here so they are not lost.

1. [x] Align plugin name and summary in the installed plugins section.
1. [x] Use display name instead of package name. See https://github.com/napari/napari-plugin-manager/pull/32
1. [ ] Fix install spinner and move plugins to available/installed list when uninstalled/installed.  see: https://github.com/napari/napari/pull/5198#pullrequestreview-1189305476
1. [x]  refactor code, one example is cleaning up the code that toggles which widgets are visible or not:
https://github.com/napari/napari/pull/5198#discussion_r1028817033

The following _Originally posted by @DragaDoncila in https://github.com/napari/napari/pull/5198#pullrequestreview-1223755876_

- [x] Align installation info,  Make a standard size?  ( I know this button adjusts by the sizes on the drop down menus held within.  Eliding may help here (see item below).
<img width="889" alt="image" src="https://user-images.githubusercontent.com/17995243/208777802-6fdbeeaa-2e88-4132-8b62-171fdab915a6.png">

- [x] Ensure author names are aligned. (maybe misaligned only with many authors and in the presence of an update button?)
<img width="915" alt="image" src="https://user-images.githubusercontent.com/17995243/208778050-b358bd20-1afd-4e70-acaf-08931af95b09.png">

- [x] Ensure very long descriptions and author lists are not cut off. 
<img width="901" alt="image" src="https://user-images.githubusercontent.com/17995243/208778152-678c26be-6bc0-4fff-86ad-0809332a161b.png">

- [x] Elide version numbers when long. 
When users have a plugin dev version installed the `Installation info` button & section is very long. We probably want to elide this
<img width="891" alt="image" src="https://user-images.githubusercontent.com/17995243/208778633-bc14aeba-e334-47ef-b031-664a3539b4b0.png">

- [x] Set height of each item.  
```
        if item.widget.install_info_button.isExpanded():
            item.widget.setFixedHeight(int(height * SCALE))
        else:
            item.widget.setFixedHeight(int(height / SCALE))
        item.setSizeHint(item.widget.size())
```
see https://github.com/napari/napari/pull/5198#discussion_r1108801401

- [x] set size of widget in settings.  see: https://github.com/napari/napari/pull/5198#discussion_r1108805490
- [ ] #79
- [x] #29. See https://github.com/napari/napari-plugin-manager/pull/45

**Comment by jaimergp** [comment]
Let's resume the work here @goanpeca.

**Comment by goanpeca** [comment]
@hiroalchem question, is your request gear towards the lineedit in the bottom of the dialog where you can type any package or drag and drop a tarball from the filesystem?

Do you mean to add extra channel besides conda-forge, is the case for plugins in the napari plugin ecosystem that they need extra channels besides conda forge?

Thanks!

**Comment by jaimergp** [comment]
I'll close this issue since most tasks have been addressed. The remaining ones have been converted to issues, namely:

- https://github.com/napari/napari-plugin-manager/issues/78
- https://github.com/napari/napari-plugin-manager/issues/79
- https://github.com/napari/napari-plugin-manager/issues/80
