### ISSUE TITLE
Move code that is specific to plugin manager from napari repo to this repo

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#33]
- [ ] `npe2api.py`
- [ ] `custom.qss` move only the rules that includes styling for the napari plugin manager

**Comment by Czaki** [comment]
>     * [ ]  `custom.qss` that includes tyling for the napari plugin manager

It will require code for theming dialog themself. Also, file cannot be moved, only specific rules.

**Comment by goanpeca** [comment]
>It will require code for theming dialog themself. Also, file cannot be moved, only specific rules.

Correct, I meant only the specific rules

**Comment by jaimergp** [comment]
@goanpeca - is this done?

**Comment by goanpeca** [comment]
Yep this is done. We can close! closing
