### ISSUE TITLE
What tool should we use by default on the plugin manager?

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#46]
Currently we have a check on the plugin manager to see if napari was conda installed then we display conda as an option to be used as installer tool, but we still use `pip` as default. Do we want to preserve this behavior or do we want to use conda as the default if we know that napari was installed with conda?

`IS_NAPARI_CONDA_INSTALLED = is_conda_package('napari')`

Any thoughts here @Czaki @jaimergp @psobolewskiPhD ?

**Comment by Czaki** [comment]
We should switch to conda if napari is conda installed.

**Comment by psobolewskiPhD** [comment]
Yeah the default should match how napari was installed.
My only hesitation is that pip checks site-packages, so if someone used the terminal and pip installed (many plugins have that in their install instructions)--or conda installed--then pip will see either preexisting stuff and supplement anything. Meanwhile, conda will happily reinstall anything pip installed. 
But still, we can't really police all that, so we should just use sane defaults.

**Comment by jaimergp** [comment]
We can add [`EXTERNALLY-MANAGED`](https://packaging.python.org/en/latest/specifications/externally-managed-environments/) to our constructor envs via `conda-pypi`. That should prevent pip from operating freely unless uses really want to yolo.

**Comment by jaimergp** [comment]
Closed by #47
