### ISSUE TITLE
Make release 

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#54]
- Create Changelog
- Create tag and pypi
- Create conda forge

**Comment by jaimergp** [comment]
* https://pypi.org/project/napari-plugin-manager/0.1.0/
* https://github.com/napari/napari-plugin-manager/releases/tag/untagged-b40c1eeb48b7995b6ef2 (let's make this non-draft @goanpeca)
* https://github.com/conda-forge/napari-plugin-manager-feedstock/pull/2

**Comment by goanpeca** [comment]
Hi @jaimergp wil do!
