### ISSUE TITLE
Plugin install on Windows a `WinError 32` show up related to some constraints file when exiting napari

### ISSUE THREAD

**Issue by dalthviz** [napari/napari-plugin-manager#63]
Trigger an operation from the plugin dialog and, at napari exit, some error related to not having access to a constraint file appears:

# A preview

![winerror_plugin_dialog](https://github.com/napari/napari-plugin-manager/assets/16781833/8f409457-a590-4bf7-a72c-9be911395a17)

# Traceback/error message

```
Exception ignored in atexit callback: <built-in function unlink>
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\dalth\\AppData\\Local\\Temp\\tmpx5py0rxw-napari-constraints.txt'
```

**Comment by jaimergp** [comment]
I think we can add some kind of ignore errors keyword in the `atexit` registration. I wonder why that file was still open; it should have been closed on exit :thinking:

**Comment by dalthviz** [comment]
Gave this a check and I think the issue is related with ignoring the file descriptor returned when using `tempfile.mkstemp` when creating the constraints file used for pip operations. Created #66 with a possible fix
