### ISSUE TITLE
How to update the napari-plugin-manager within an existing napari installation

### ISSUE THREAD

**Issue by jaimergp** [napari/napari-plugin-manager#71]
So we have this uncoupled `napari-plugin-manager`. It technically allows us to update it without having to update napari itself. Should we provide an easy way to `self-update` the manager? Otherwise users would have to fire up a CLI to update the napari environment and who knows what will happen there :P

I'm thinking either a button somewhere, or a message when a new version is available, or something similar. Hopefully the update is trivial and doesn't involve too many changes in dependencies.

WDYT? This is not urgent but came to mind while thinking about the distribution model.

**Comment by psobolewskiPhD** [comment]
I think this would be great, one of the boons of the split out IMO

**Comment by psobolewskiPhD** [comment]
honestly, it could just be in the list, so it would be listed at the top with console, so the user could see there is an update

**Comment by jaimergp** [comment]
I like it. Maybe it's time to make it an actual napari plugin, or do we want to special case it?

**Comment by psobolewskiPhD** [comment]
> I like it. Maybe it's time to make it an actual napari plugin, or do we want to special case it?

I don't have strong feelings here. making it a plugin would be very meta.

**Comment by jni** [comment]
I love seeing this close notification! 🚀 

Just want to drop in and say — I have been very hands off with this repo because I am overwhelmed enough with the main one (and docs), but I really love and appreciate the progress you have all made here, and especially all the upstreaming to related tools. ❤️ Thank you! 🙏
