### ISSUE TITLE
Investigate flickering and slowness on filter search while plugins are loading

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#76]
>I see with the changes here and with latest main a little freeze when filtering things, maybe is worthy to create an issue to track that? Related more specifically with the flickering, I think I'm able to see that behavior in all the versions that I checked. Maybe that is related with changes caused due to other plugins being loaded which change the width used for other fields like author and then cause the plugin description space to be shorter? Maybe creating an issue for that could be worthy too? 🤔

https://github.com/napari/napari-plugin-manager/pull/31#issuecomment-2233664828

**Comment by psobolewskiPhD** [comment]
I just did a fresh pull from main c48deb219038134fcbcbfa0e0fe9344781f6c84b
here's what I get:

https://github.com/user-attachments/assets/7703ba91-1d79-4500-ae83-6fd128ae1fd6

If i search for `zar` i don't get flickers, I think it's when the filter contains something that has already been loaded.
