### ISSUE TITLE
Update MANIFEST to include the images files that are now missing in the PyPI README

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#91]
https://pypi.org/project/napari-plugin-manager/#description

<img width="999" alt="Screenshot 2024-07-31 at 12 48 59 PM" src="https://github.com/user-attachments/assets/bb58dace-279f-4f2b-b99a-7baa9f8376dc">

**Comment by Czaki** [comment]
Including files to manifest will not help. There is a need to provide an absolute path to image on some remote server (like github).

**Comment by goanpeca** [comment]
Indeed, will fix it :)
