### ISSUE TITLE
Make a new release for v0.1.1

### ISSUE THREAD

**Issue by goanpeca** [napari/napari-plugin-manager#99]
This release includes minor bug fixes and adds the napari classifier to start testing updating the plugin manager within itself.

There might be some issues on windows, but I will start debugging those as part of the release

**Comment by jaimergp** [comment]
LPT: https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-update-version

**Comment by dalthviz** [comment]
Hi there, just in case, did the release (GitHub release/tag + conda-forge issue to generate version update) and created a PR (https://github.com/napari/napari-plugin-manager/pull/101) adding a `RELEASE.md` to describe the steps needed to trigger/do a release. Let me know if there are any changes or further steps that should be done @jaimergp @goanpeca
